image:
  repository: localhost:5000/url-shortener
  tag: latest
  pullPolicy: Always

replicaCount: 1

domain: qr.dcommunity.space
apiKey: "how long would it take to think about such a long api key"

service:
  name: url-shortener
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  name: url-shortener-ingress
  host: qr.dcommunity.space
  certResolver: le

persistence:
  enabled: true
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClass: local-path
