apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8000
          env:
            - name: DOMAIN
              value: "{{ .Values.domain }}"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: url-shortener-secret
                  key: API_KEY
          volumeMounts:
            - name: cache-volume
              mountPath: /app/url_cache
      volumes:
        - name: cache-volume
          persistentVolumeClaim:
            claimName: url-shortener-cache
